modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_islands"
version = "${version}"
displayName = "VS Islands mod"
authors = ["ewoudje"]
description = '''
Islands!
'''
logoFile = "icon.png"

[[dependencies.vs_islands]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_islands]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_islands]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_islands]]
modId = "lasagna"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"